=== curtis-cantrell/newGitTest/web/cc-webapp-config.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="cc-web-app" type="cc-web-appType"/>
    <xs:complexType name="url-mappingType">
        <xs:sequence minOccurs="0">
            <xs:element type="xs:string" name="url-pattern"/>
            <xs:element type="xs:string" name="tenant"/>
            <xs:element type="xs:string" name="domain"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="url-mappingsType">
        <xs:sequence>
            <xs:element type="url-mappingType" name="url-mapping" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="mgw-urlsType">
        <xs:sequence>
            <xs:element type="xs:string" name="mgw-url" maxOccurs="unbounded" minOccurs="1"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="cc-web-appType">
        <xs:all minOccurs="1" maxOccurs="1">
            <xs:element type="mgw-urlsType" name="mgw-urls" minOccurs="1" maxOccurs="1"/>
            <xs:element type="xs:string" name="storyboard-url" minOccurs="0" maxOccurs="1"/>
            <xs:element type="xs:string" name="retouch-url" minOccurs="0" maxOccurs="1"/>
            <xs:element type="xs:string" name="analytics-url" minOccurs="0" maxOccurs="1"/>
            <xs:element type="xs:string" name="workshop-url" minOccurs="0" maxOccurs="1"/>
            <xs:element type="xs:string" name="supervisor-url" minOccurs="0" maxOccurs="1"/>
			<xs:element type="xs:string" name="ruleeditor-url" minOccurs="0" maxOccurs="1"/>
			<xs:element type="xs:string" name="writer-url" minOccurs="0" maxOccurs="1"/>
			<xs:element type="xs:string" name="bca-url" minOccurs="0" maxOccurs="1"/>
			<xs:element type="xs:string" name="orchestrator-url" minOccurs="0" maxOccurs="1"/>
            <xs:element type="url-mappingsType" name="url-mappings" minOccurs="0" maxOccurs="1"/>
            <xs:element name="update3-access-flag" type="xs:string"  minOccurs="0" maxOccurs="1"/>
            <xs:element name="deployment-type"  minOccurs="0" maxOccurs="1" default="prod">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="dev"/>
                        <xs:enumeration value="prod"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:all>
    </xs:complexType>
</xs:schema>

=== curtis-cantrell/newGitTest/Tomcats/OTDS/webapps/ROOT/config/cc-webapp-config.xml
<?xml version="1.0"?>
<!-- 16.6.0_GA_443 -->
<cc-web-app xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="../xsd/cc-webapp-config.xsd">
    <!-- we can specify multiple mgw-url -->
    <mgw-urls>
        <!-- we can specify multiple mgw-url, first order of MGW priority will be based on the order of the
         below configured tags. i.e First configured url will be given highest priority and if that fails second one will
         be picked up and on. If all mgw-urls fails, error message will be shown.
         -->
        <mgw-url>https://thecompany.com:28801/management/rest/v1/servicegateways</mgw-url>
		<!-- <mgw-url>https://thecompany.com:28801/management/rest/v1/servicegateways</mgw-url> -->
        <!--<mgw-url>https://localhost:29400/management/rest/v1/servicegateways</mgw-url>
        <mgw-url>https://localhost:30800/management/rest/v1/servicegateways</mgw-url>
        -->
    </mgw-urls>
	

    <!-- Storyboard url, should be one and is not a mandatory tag -->
    <storyboard-url>https://thecompany.com:8443/storyboard</storyboard-url>

    <!-- Retouch url, should be one and is not a mandatory tag -->
    <retouch-url>https://thecompany.com:8443/retouch</retouch-url>
    
    <!-- Workshop url, should be one and is not a mandatory tag -->
    <workshop-url>https://thecompany.com:8443/workshop</workshop-url>
    
    <!-- Supervisor url, should be one and is not a mandatory tag -->
    <supervisor-url>https://thecompany.com:8443/supervisor</supervisor-url>
    
	<!-- Rule editor url, should be one and is not a mandatory tag -->
	<ruleeditor-url>https://thecompany.com:8443/ruleeditor</ruleeditor-url>	   
	
	<!-- Writer url, should be one and is not a mandatory tag -->
	<writer-url>https://thecompany.com:8443/writer</writer-url>
	
	<!-- Orchestrator, should be one and is not a mandatory tag -->
	<orchestrator-url>https://thecompany.com:8443/orchestrator</orchestrator-url>	
	
	<!-- BCA / Exstream content launcher url, should be one and is not a mandatory tag -->
	<bca-url>https://thecompany.com:8443/exstream</bca-url>
	
    <!-- use url-mappings to create friendly urls -->
    <!--<url-mappings>
      <url-mapping>
           <url-pattern>tenant1</url-pattern>
           <tenant>9B4AAD3B-E870-1E45-A5A8-B28A3A62C3A7</tenant>
           <domain>C8138B90-9AAE-8C44-9D70-F015CC6277E1</domain>
       </url-mapping>
       <url-mapping>
           <url-pattern>tenant2</url-pattern>
           <tenant>9B4AAD3B-E870-1E45-A5A8-B28A3A62C3A7</tenant>
           <domain>C8138B90-9AAE-8C44-9D70-F015CC6277E1</domain>
       </url-mapping>

    </url-mappings>-->

    <!-- If the MGW is configured with self signed certificate use dev otherwise prod.
      This element takes only two values dev and prod -->
    <deployment-type>dev</deployment-type>
</cc-web-app>
